--------------------------------------------------------
--  Constraints for Table PHOTOS_EXIF
--------------------------------------------------------

  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" ADD CONSTRAINT "PHOTOS_EXIF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" MODIFY ("FILESIZE" NOT NULL ENABLE);
  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" ADD CONSTRAINT "PHOTOS_EXIF_GPS" CHECK (GPSLatitudeRef IN ('N', 'S', NULL) AND GPSLongitudeRef IN ('E', 'W', NULL) AND GPSAltitudeRef IN (0, 1, NULL)) ENABLE;
  ALTER TABLE "YOURSCHEMA"."PHOTOS_EXIF" ADD CONSTRAINT "PHOTOS_EXIF_MIME" CHECK (MimeType IN ('image/gif', 'image/jpeg', 'image/png', 'image/tiff')) ENABLE;
